###
GET http://localhost:8000/positions

###
POST http://localhost:8000/positions
Content-Type: application/json

{
    "name":"front dev",
    "user_id":"1",
    "team_id": "1"
    
}

###
DELETE http://localhost:8000/positions/1
