###
GET http://localhost:8000/users

###
POST http://localhost:8000/users
Content-Type: application/json

{
   
    "firstname":"Calvin",
    "lastname": "Hyacinth"
    
}

###
DELETE http://localhost:8000/users/4

