get  http://localhost:8000/users
Content-Type: application/json

###
POST http://localhost:8000/users
Content-type: application/json

{
    "firstname": "John",
    "lastname": "Doe"
}

###
DELETE http://localhost:8000/users/4
Content-type: application/json

###
get  http://localhost:8000/teams
Content-Type: application/json

###
POST http://localhost:8000/teams
Content-type: application/json

{
    "owner_id": 1,
    "name": "Bad Cat"
}

###
DELETE http://localhost:8000/teams/1
Content-type: application/json

###
get  http://localhost:8000/projects
Content-Type: application/json

###
POST http://localhost:8000/projects
Content-type: application/json

{
    "team_id": 1,
    "title": "Project"
}

###
DELETE http://localhost:8000/projects/10
Content-type: application/json

###
get  http://localhost:8000/positions
Content-Type: application/json

###
POST http://localhost:8000/positions
Content-type: application/json

{
    "name": "Sound ingeener",
    "user_id": 1,
    "team_id": 1
}

###
DELETE http://localhost:8000/positions/10
Content-type: application/json

###
POST http://localhost:8000/login
Content-type: application/json

{
    "firstname": "Timothee",
    "lastname": "Augustin"
}